mod themida;

use std::sync::atomic::{AtomicU64, Ordering};

use binaryninja::{
    background_task::BackgroundTask,
    binary_view::BinaryView,
    command::register_command,
    function::Function,
};
use log::{debug, info};

use themida::ThemidaSpotterCommand;

pub type CodeEntryDestRange = std::ops::Range<u64>;

const THEMIDA_SPOTTER_PLUGIN_NAME: &str = "themida-spotter-bn";
const THEMIDA_SPOTTER_TAG_NAME: &str = "Themida's obfuscated code entries";
const THEMIDA_SPOTTER_TAG_ICON: &str = "🛡";

#[derive(Debug)]
pub enum CodeEntryDescription {
    // VMENTER (RVA)
    VMEnter(u64),
    // MUTENTER (RVA)
    MUTEnter(u64),
}

impl CodeEntryDescription {
    pub fn rva(&self) -> u64 {
        match self {
            Self::VMEnter(rva) => *rva,
            Self::MUTEnter(rva) => *rva,
        }
    }

    pub fn type_name(&self) -> &str {
        match self {
            Self::VMEnter(_) => "Code entry (Virtualized)",
            Self::MUTEnter(_) => "Code entry (Mutated)",
        }
    }
}

pub fn search_for_code_entries<
    F: Send
        + Sync
        + 'static
        + Fn(&BinaryView, &Function, &[CodeEntryDestRange]) -> Option<CodeEntryDescription>,
>(
    view: &BinaryView,
    analyze_function: F,
    target_sections: Vec<CodeEntryDestRange>,
) {
    let view = view.to_owned();
    let _thread = std::thread::spawn(move || {
        let task = BackgroundTask::new(&format!("({}) Initializing...", THEMIDA_SPOTTER_PLUGIN_NAME), true);
        search_for_code_entries_task(view.as_ref(), analyze_function, target_sections, &task);
        task.set_progress_text("");
        task.finish();
    });
}

fn search_for_code_entries_task<
    F: Send + Sync + Fn(&BinaryView, &Function, &[CodeEntryDestRange]) -> Option<CodeEntryDescription>,
>(
    view: &BinaryView,
    analyze_function: F,
    target_sections: Vec<CodeEntryDestRange>,
    task: &BackgroundTask,
) {
    info!("Searching for obfuscated code entry patterns...");

    let function_count = view.functions().len();
    debug!("Processing {} functions.", function_count);
    let current_progress = AtomicU64::new(1);
    let mut code_entry_descriptions = Vec::new();

    for func in view.functions().iter() {
        if task.is_cancelled() {
            info!("Operation was cancelled");
            return;
        }

        if let Some(entry_desc) = analyze_function(view, &func, &target_sections) {
            code_entry_descriptions.push(entry_desc);
        }

        let progress_text = format!(
            "({}) {} / {} functions processed",
            THEMIDA_SPOTTER_PLUGIN_NAME,
            current_progress.load(Ordering::Acquire),
            function_count
        );
        task.set_progress_text(&progress_text);
        current_progress.fetch_add(1, Ordering::Acquire);
    }

    // Get or create tag type
    let vm_entry_tag_type = view
        .tag_type_by_name(THEMIDA_SPOTTER_TAG_NAME)
        .unwrap_or_else(|| view.create_tag_type(THEMIDA_SPOTTER_TAG_NAME, THEMIDA_SPOTTER_TAG_ICON));

    // Create tags for each obfuscated code entry found (if any)
    for code_entry_desc in &code_entry_descriptions {
        view.add_tag(code_entry_desc.rva(), &vm_entry_tag_type, code_entry_desc.type_name(), false);
    }

    info!(
        "Found {} obfuscated code entry locations. Tags have been set at the corresponding addresses.",
        code_entry_descriptions.len()
    );
}

#[no_mangle]
pub extern "C" fn UIPluginInit() -> bool {
    let command_name = format!(
        r"{}\Find obfuscated code entries (3.x)",
        THEMIDA_SPOTTER_PLUGIN_NAME
    );
    register_command(
        &command_name,
        "Look for obfuscated code entry patterns generated by Themida 3.x",
        ThemidaSpotterCommand {},
    );

    true
}
